# Generated by Django 4.2.13 on 2024-07-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(default='perfiles/default_profile.jpg', upload_to='perfiles/'),
        ),
    ]
