# Generated by Django 4.2.13 on 2024-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='imagen',
            field=models.ImageField(default='media/perfiles/default_profile.jpg', upload_to='media/perfiles/'),
        ),
        migrations.AlterField(
            model_name='fotoalojamiento',
            name='imagen',
            field=models.ImageField(upload_to='media/alojamientos/'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='imagen',
            field=models.ImageField(default='media/perfiles/default_profile.jpg', upload_to='media/perfiles/'),
        ),
    ]
