# Generated by Django 4.2.13 on 2024-07-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuni', '0002_user_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
