# Generated by Django 4.2.13 on 2024-07-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuni', '0003_user_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='servicios',
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='servicios',
            field=models.ManyToManyField(related_name='alojamientos', to='casuni.servicio'),
        ),
    ]
