# Generated by Django 4.2.13 on 2024-07-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuni', '0004_remove_alojamiento_servicios_alojamiento_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
