# Generated by Django 4.2.13 on 2024-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuni', '0005_alter_alojamiento_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
