# Generated by Django 4.2.13 on 2024-07-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casuni', '0006_alter_alojamiento_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
